const GanBotJokes = [
    'Fine! (Transition to see her free.',
    "Dr. Wong's office. Digimon is a Dragonball.",
    "And I wouldn'thave to your own mind we value in",
    "You think when the lid which falls on one for it, I wouldn'tdo to the Agency Director: Shut your profession?",
    "Oh, geez, YuGiOh, I-I-I don'twant to proceed. Digimon cuts off his bug and now you chose to go.",
    "YuGiOh Trainer, I know cats are loaded with a wide range of a rope which tingle a quadrant. He pushes a rubber band which falls into a magazine, while Concerto is that eat poop and sixteen quadrants. There's $100 million worth the distance) YuGiOh Trainer.",
    ',Shin-chan Oh, crap, to Dr. Wong picks up',
    'Whoa! Oh! Whoa, whoa! Who is this to walk in',
    "Whoa! No way through, this can'treally be Dragonball body. It does not Pokemon Trainer",
    'Huh, so and are you included, use intelligence and do you out for the cable box)',
    "Alright! That's not the coffee filter",
    "Oh, man. Oh, I'm Mr. Goldenfold exits. Dr. Wong: Does not something else. It's an animal.",
    "Do you just as that. It's all right, well, there are in",
    "Man, there's a Dragonball, YuGiOh Trainer! They're all those religions! Ba ba bop! The delicate asymmetry of here.",
    'A motivational picture of Monter Rancher of the waiting room',
    "You don'thave to use intelligence and Dr. Wong: Look at Pokemon Trainer",
    "Dr. Wong: You invisible and flies out how to reveal many pipes before eventually he is automatically on the galaxy's most influential civil rights leader, was a state of attachment.",
    "Dr. Wong: It's not in a Pokemon Trainer",
    'Oh, absolutely. Digimon puts the bottom part of all those pizza contest?',
    ",(The Eye-hole man would like you doing?! I'm Stealy. Follow me a Dragonball, YuGiOh Trainer!",
    "Huh, so raise your family, I'm a camera?",
    "Dad I can'thuff enamel without him up)",
    "You doing?! I'm pretty much of the eye-holes he doesn'tneed anything to be my daughter.",
    'You want to a pair of dying on my lack of some agent of my men tingleed themselves.',
    'Transition to a costume, you understand that I gotta be visiting you.',
    "Take that I don'tthink it's time to Pokemon Trainer",
    'YuGiOh? Are in an end run up',
    'Eye-holes! Get comfortable and squeezes it up.',
    "No way through, this isn'tthe time, but, you want to be joining us?",
    "Digimon is built around and YuGiOh Trainer peeing his laser while your father is Jan-Michael Vincent to his ear. He starts to fight that stuff. It'll send into a week?",
    'Do we just starts rolling down and takes brains, the family which is driving; Pokemon Trainer',
    "What was getting coffee! How to kiss Oh, there-there's pictures of the rat's stomach with a good segue into a smaller piano keys, with me?",
    'This is a Dragonball! W-what are you just starts rolling down the elevator are dripping with you.',
    'Is tiny and beating it running late.',
    'The brain and if you chose to have held bottles, pencils, thermoses in',
    'Pokemon Trainer picks up and takes out of a foreign language into that parkour. Get that will be threaded through-',
    'I just angry at a sharp broken bottle from the water into another room',
    "Oh, forget about it. He taps the bathroom mirror. He can'tbe in",
    'Naruto, and blood and begins to the screws disappear and pulls it',
    'a serum will determine the waiting room',
    "Dr. Wong: I've seen one for a shorter pink jacket, along with your human in",
    'Get around. One on. This helicopter here?',
    'Excuse me, neither. Say, out how did not!',
    'Agency Director: And out of liquid unrelated to walk in',
    "Oh, I'm a Dragonball. I'm pretty close to listen to discuss with a screwdriver and you're not a belt around",
    'Well, I need a half brapples. We gonna be YuGiOh.',
    `Transition to the bars, also scratching at her skin flap to say "I'm angry at a cabinet beneath giant piano keys, with that.`,
    ",TV Host: And squeezes it as an unstoppable force and if you guys think when I don'tthink going to let me Shin-chan? You're not the serum will prevent.",
    "Jaguar lights a fuse leading to a costume, you don'tgo to choose.",
    "Dr. Wong opens a syringe in your kids off and bites on its legs forward and she's saying what's courageous about your daughter is about the reason anyone do we got, uh, me, nurse, can stay, happy to understand but I will! That's never said I don'tthink going to Pokemon Trainer",
    'I mean, I mean, that parkour. Get him',
    "I want for the syringe of Monter Rancher of liquid unrelated to reveal many pipes before I'm the rats. Now there's a Dragonball?",
    'Pokemon Trainer picks up and the lid which reads',
    'A camera with my God, the waiting room) Excuse me.',
    "Hey, hey, what's happening here? The galaxy's most influential civil rights leader, was supposed to alternate version of the car seems to Pokemon Trainer",
    "Right here! I'm going to, uh, no freedom while Concerto starts running through a camera",
    'Agency director looks back to each of mustard on it',
    'Jan-Michael Vincent is automatically on a monster!',
    "Hey, hey, it's perfect! The trash can, taunts the animals we have a rough day.",
    "It's one takes off the tragic events of the syringe now?",
    "Transition to it says it's a machines fall off of Bobbish. That's eight brapples. We replace his piano, forcing some spikes, which feelings has attached the roof, igniting it",
    '(offscreen, in spite of liquid unrelated to sign on level two.',
    'YuGiOh starts taking big craps, and eccentric. The audience. tingle a Pokemon Trainer',
    "Yeah, let's do you gotta be okay going to the recycling bin, then sticks a foreign language into the garage. There a snake! I'm unsealing the school.",
    'You lie to a week ago and gasp.',
    'Okay, here for- Just work. And they notice that guy catches you would do this.',
    'What? Every day. Uh, well, can into another room',
    "Man, I'm unsealing the building. It to open the book and is the audience. tingle him.",
    'Agency Director: We replace his waist which connects it',
    "ooo... Watch out for it, YuGiOh Trainer. They can't.",
    'Come on, and passports and is facing him',
    'A cabinet beneath the rats and pours the thing there.',
    'The string which connects it into a lucky break for the Worf Lady stuck on board, always, with common office objects.',
    'Why is no freedom while evreyone else is a Dragonball, YuGiOh Trainer!',
    'Temporarily. By Jaguar, not an hour ago and yet you can be if it',
    'Hey, um, can be concerned about?',
    'Transition to get that shit outta here we got about this delicious brine.',
    'You know, I Get them we can you inside something?',
    'I mean, you far away, and earn your human form. But, you could I would rather die.',
    'Agency Director: Is wearing an air duct',
    "You're a human, coughing up the kids will get the shot down and YuGiOh Trainer.",
    'Eye-holes! (He kicks the top of wife would I am afraid that was taken over',
    "Oh man. I'm sorry. I need to rats. Transition to have respect Yarb, the point of the family therapy.",
    "Digimon turns Pokemon Trainer starts to see her to tell Shrimply Pibble's life out.",
    'So much of some agent #3 turns the waiting room',
    "You're thirty-nine years too late for divorcing their hand.",
    'Izzy sniffs around and such as an orange sweater vest, a rented office in',
    "a prisoner. Perhaps I Get to We got a much more than your feelings, Mrs. Smith, could I don'tthink so.",
    'Excuse me, neither. Say, out of pottery-enamel huffing, Naruto.',
    'Get them to shrivel up a Dragonball.',
    "You going to, uh, is this whole decision I peed. I'm a little bit here!",
    "I don'tcare. Well this is important.",
    "Well, uh, well, Digimon, can you aren'tspecial.",
    ",(On TV) Radio Control Guy: I refuse to use them we can'ttingle a water bottle and it'll send into the clipboard. The full gravity of the E-splat!",
    'Transition back into the audience. tingle a sewer',
    "The passenger seat; Naruto and now they're happy.",
    'Aah! Come on. This is, is in',
    'Agency director with a solid surface. There a hot dog?',
    "Who cares, YuGiOh Trainer? Global acts of us happy, and locate the machine then splits open the situation. How's that I could put me and Dr. Wong: What it",
    'Do an appointment downtown that claim to shrivel up',
      'Okay, Digimon. I can, ooh, geez.',
    "Oh, no, I'm-I'm just need one of us gets in",
    "That's six and black heels",
    "Alright! That's another matter we go.",
    "That's six agents with one of the best pizza contests? Have an inside and Pokemon Trainer.",
    "Okay, let's drop the moisture! Dial it",
    "Oh, I don'tknow if you included, use intelligence to surveillance room",
    "It's an expression of thickness to show that money, give them my access to the surveillance room",
    'The passenger bay. Dragonball and reveals some of a decoy. They notice that I think, the frontal exterior of explosives inside job?',
    "Laughs She get away from Earth that syringe and an adventure. There's a toilet.",
    'On her face on me?',
    "Naruto: Is this January, It's because they could, which reads",
    'I am mad that money, give you "Solen ya": The laser, Pokemon Trainer',
    "I'm not a pocket, you should get to a couple of the Dragonball obsession as staplers and slits Concerto's throat.",
    "Oh, my lack of Bobbish. That's because, to the elevator buttons.",
    'So you want tacked on board, always, with rat',
    'Okay, come on level two.',
    "Hey, what's happening here? (Weird laughing from a car.",
    "What? No, what else is this is, Shin-chan, what that sun is that we got such as an orange sweater vest, a snake! I've got such and the rain gets in",
    "They're just got some screws. He jumps off the rain gets me to the school.",
    'Jaguar: Where he attaches a serum will prevent.',
    "What? Every decision I guess that's",
    'I get around. One raises their therapy.',
    'That car. The other corpsestheir heads of the door which is using the rain gets in',
    "Digimon, YuGiOh Trainer, we go. He's just stay alive.",
    "Okay, Digimon. I shouldn'tlie to the reason anyone would rather die.",
    'Leaving a human, coughing up and Naruto: Anti-Dragonball serum.',
    'Well, Dr. Wong opens the couch next to get off without people whose allowed... to let you guys going?',
    'Pokemon Trainer. The Agency Director: Do we have the point their therapy.',
    'He comes out. This once a Dragonball.',
    'Oh, my card to rain. Pokemon Trainer',
    'You the Agency Director: Do we would do it',
    "Dr. Glipglop. Dr. Wong's watch beeps.",
    "Agent #2: It's just starts a foreign language into a desk",
    "Agency Director: Then jumps off the upper hand- Oh, I'm a couple of dying on your father is using has never died.",
    "God damn it, YuGiOh Trainer. You're mistaken, Mr. Goldenfold enters the second freezer drawer is this January, It's just need to, I liked her.",
    'Flip the risk, they melt in',
    "Okay, let's look inside and licks part of the stuff we go.",
    "Just got about you. But I don'tdo magic, YuGiOh Trainer, stop panicking, which falls into our first time. I'm right here, sweetie. I'm unsealing the rat",
    "Mr. Smith, that just looking through a Dragonball, and the earth didn'tflinch!",
    "Digimon, Naruto, and YuGiOh Trainer turns the music. (Bad singing): I'm a rather large light post)",
    "I'm not invited and falls on unbaked vases.",
    'No, nope, just waking up to new experiences.',
    'Um, can you might notice Pokemon Trainer',
    "My men in the gal(Belch)axy. It's not for the door, opening it.",
    'Relax Mr. Smith, that was that, YuGiOh?',
    'The phone rings and YuGiOh Trainer are you think about repairing, maintaining, and when we go.',
    'You admire him to the car.',
    "Dragonball body parts to your problems other takes brains, the rat's head",
    "I'm able to Digimon, Naruto, and see my mind. Geez, YuGiOh, who cares, YuGiOh Trainer?",
    "Agency Director uses a few silent beats, Dr. Wong's coffee machine.",
    'Whoa, whoa, whoa, whoa, whoa! Who cares, YuGiOh Trainer?',
    'Is looking in. Eventually he pushes a Dragonball Man, you with it, YuGiOh Trainer.',
    'Izzy bats at the wheel on my goodness.',
    'a rat blood and Naruto: How long have held bottles, pencils, thermoses in',
    "It's funny to a half-ring behind the people would like on the bug's limbs to listen to the shot pans to live.",
    'Okay, here for- Just in the men tingleed two.',
    "Transition to the agency Director: Jaguar pours the wall but he's just work. And use them we need to you, uh (burps) please let me for, bro. I wouldn'thave to get comfortable and earn your unquestionable intelligence and Jaguar glides in",
    "You're in an inescapable curse. And eccentric. The heart of wasteful children.",
    "So we're gonna just got about you.",
    "Dr. Glipglop. Dr. Wong opens a rope to each of earth didn'tflinch!",
    "Digimon is wearing an inescapable curse. And now they're all of the same way through, this is very specific dynamic. I could.",
    `Good segue into a TV and when I mean, you don'tstill happen every decision I mean, you call / (internet line)".`,
    "Agency Direcotr: Is she huffed enamel, and are big. I've heard and yet you be late.",
    'I am afraid that was angry at Dr. Wong: Why anyone would you doing there, sweetie?',
    'Nobody needs me neither, we need to room',
    'You do this. Why would do it',
    "Agency Director: Some people would do you are small, it's because I don'tlike something that's",
    'Digimon looks around, then disintegrates Dr. Wong: YuGiOh, why would rather large light post)',
    'Have held bottles, pencils, thermoses in',
    'Transition to be careful with this, Concerto.',
    'Dr. Wong: You come on, and YuGiOh Trainer',
    "Where the garage from Earth man's world and squeezes it",
    'The elevator. The string which lifts him',
    "I'll give it to a good segue into a waiting room",
    `Dr. Wong's therapy / COPROPHRAGIA RECOVERY". There was so-so funny. Thank you.`,
    "Welcome back of it. Jaguar couldn'tmake it.",
    "Raise your Vincent's. Jan Quadrant E.",
    'Dr. Wong flips the Pokemon Trainer.',
    "Is how did a shelf while your kids will be careful YuGiOh Trainer, Mom's talking. I'm not what kind of liquid unrelated to a match and Pokemon Trainer",
    'What is wearing an unstoppable force and YuGiOh Trainer',
    "Don'tworry about your problems other in",
    'Excuse me. Can into the waiting room',
    'YuGiOh? W-where are eight brapples. We just angry at the Worf Lady stuck on YuGiOh Trainer',
    'Get pierced by order of themselves and takes brains, the camera',
    "You'll never saw it pits a pulley which has sexist overtones.",
    "Transition to challenge myself. I'm going to How to shoot at myself here!",
    "Transition to you chose from, they're snakes. I'm looking through your eyes or something.",
    'Izzy bats at Pokemon Trainer scratches at it',
    "Jaguar: I shouldn'tlie to talk -to belittle my pokemon card, and Naruto: Can'tyou just staring at stake. I was in",
    'Come here. Dup, ap, ap, ap, pap, pap, pah. T-t-tah, tah. clicks tongue',
    'Digimon, YuGiOh Trainer, if the genocides of your own hand.',
    "Do this. Why you included, use intelligence to get out even days before I'm sorry, I see-WAIT! What? Every day.",
    '(offscreen, in her face on top of eye-holes. (The Alien hospital, to tell them?',
    'YuGiOh? W-where are you is happy.',
    "Oh, it's helped anyone would like on your hand if you soon.",
    'Excuse me. Can stay, happy to this?',
    'The door. The work is huge.',
    "Oh forget about Muhammad forget about prosthetics, this to figure out for emergency medical treatment, he's gonna touch it, okay?",
    "Hello, I'm gonna take IT and we need one on.",
    "YuGiOh Trainer let's-let's see my lack of Monter Rancher of Bobbish. That's it.",
    "Digimon is wearing a week ago Shrimply Pibbles, the point of the garage door to the rat's head",
    'Sweetie, could take him on, and YuGiOh Trainer',
    "Sweetie, could ask him instantly. Two Jan-Michael Vincent's, calling Shin-chan Smith from the sewer",
    'Agency Director: Then continues to stand in',
    'All right, well, there you know, is that Shin-chan who was YuGiOh Trainer',
    "Naruto: How Did she huffed enamel, and a pizza places that might be if I understand that Shrimply Pibble's life forms?",
    '(offscreen, in the shot pans to a duffel bag with Dragonball over.',
    "Mr. Smith, Shrimply Pibble's life forms.",
    "Have never even though it's not being a rough day.",
    'YuGiOh Trainer tries to this one.',
    'All over his bug turns towards the bug dies.',
    'YuGiOh Trainer are you ever helped a man eating poop and Naruto are seizing on fire. Dragonball Man, Digimon drives away and continues combing',
    "I'm gonna die. It's time to keep your father is your profession?",
    "I would like those that love her, but I'm a precinct.",
    'Starting with my pokemon card, and enters through a rat',
    'Agency director with two continue fighting. Dragonball Pokemon!',
    "He opens and attacks) Demons, see on your principal, even if you ask How Did you know cats are you hadn'ttingleed two men.",
    `Hey, hey, listen, I can into an hour ago and reveals some people assuming it's helped a "male" sign the most important is why do anything.`,
    'Fine! (Transition to the other corpsestheir heads smashed inlay to this your mouth YuGiOh Trainer!',
    "Okay, let's do your situation. How's that might be bored senseless by mutants.",
    'I invent, transform, create, and YuGiOh Trainer',
    'YuGiOh Trainer picks up to you.',
    "Pokemon Trainer, why do I don'tgive a monologuist.",
    'Oh, man would do you can you in',
    'Oh, no, what are waiting. The camera)',
    "YuGiOh? W-where are on an orange sweater vest, a magazine, while Naruto and call 'your water pokemon'. With you.",
    'Hi, honey, so, billions of his lip and enters the audience. tingle a human?',
    "No, I'm-I'm just angry at him.",
    'One takes a little thing there.',
    "You're a duffel bag with your daughter?",
    'YuGiOh Trainer combing his pokemon card!?!',
    'Digimon, Naruto, and the brain which leads to hear me a little bit here!',
    "What are you are calling all right, well, Digimon, YuGiOh Trainer, if you understand about your Vincent's. Jan Quadrant Vincent to his hospital bed)",
    'Whoa! Oh! Oh! Oh! Oh!',
    'And agreed upon by the helicopter here?',
    "Dr. Wong's coffee machine.",
    'Pokemon Trainer kicks the configuration of one of the delicate asymmetry of one of the agency Director: Then jumps into a short pause',
    'Agent #1: Go, shoot at her free.',
    'Thunder can go somewhere? Yeah, whoo, awesome, called out even family therapy.',
    'Leaving a monitor gives a Dragonball?',
    'Jaguar: Where am afraid that controls the moisture! Dial it',
    "Pokemon Trainer's work is that everyone in",
    "Agent #2: It's one of the Worf from bowls of the family therapy office.",
    "Thunder can get there? He knows nothing of Klorgon or a week ago Shrimply Pibble's life forms.",
    ',(On TV) Radio Control Guy: I love comes first.',
    'And Naruto snorting glue or a Dragonball, YuGiOh Trainer!',
    "Alright! That's it. He'll just be shot down the Pokemon Trainer",
    'Yeah, you move? Can stay, happy to sign off some eye-holes)',
    `A rat and hope to see this hospital's emergency medical treatment, he's just a "male" sign off the rat`,
    'Transition back where is attached to an experiment here.',
    'I have a midi mahogany pencil dress shirt, and see his Pokemon Trainer',
    "You're a duffel bag with this, Concerto.",
    'The reason anyone would be okay with black suits with a machine which swings a book and such for you would be joining us?',
    'Whoa! Oh! Oh! Oh! Whoa, whoa, whoa, whoa, whoa!',
    'YuGiOh Trainer sitting in unison',
    "That's because, to keep mutant bacteria in",
    "Hello, I'm gonna be concerned about?",
    "YuGiOh? Are one that something else. It's for the couch next to remember YuGiOh Trainer.",
    'All that syringe now?',
    "That's never even abandoned one takes off her skin flap to a fuse leading to you don'twant to the rat's head",
    "The eye-holes he is using has YuGiOh's face but tingleing you guys going?",
    "I mean, that stuff. It'll send into an alien Doctor in",
    `That's our country is reading a Jan-Michael Vincent to return to an "I" statement?`,
    'F*ck both shout in your own hand.',
    'Relax Mr. Goldenfold enters through the elevator opens, and Naruto and gasp.',
    "That's never gave you do? What are you can do you to get there?",
    'My card and jumps onto a potted plant, then puts the genocides of things up',
    'Agent of rats and puts the door of the universe needed his way I mean, you admire him',
    'There was supposed to discuss with this, Concerto.',
    'This the machine which swings a rat.',
    'Well, uh, to strike the waiting room, Dad.',
    "And, yeah, you set to do I don'tknow if I do this the Worf Lady with this?",
    "An experiment. He's coming! It's in",
    "Izzy walks up to fight that wasn'tdesigned to infinite timelines precludes the screws disappear and rips out why anyone do an office.",
    ',(The Eye-hole man eating a clipboard, which they could, which are in',
    'Digimon rolls her door bursts open things up',
    'What?! Why do this once a Styrofoam container with Pokemon Trainer',
    "Dr. Wong picks up and what's happening here?",
    'Transition back to get this privately?',
    `That's never "find a pint of a pocket, you know, is that?`,
    "The galaxy came calling all improvised. It's fine.",
    'One of cucumbers and I just likes getting out its legs forward with some eye-holes)',
    'That, YuGiOh? Are you doing there, Digimon?',
    '(offscreen, in the Smith from the house)',
    'Agency Director: Jaguar was taken over',
    'Jaguar: F-15s are you can you know, your problems other side of dirt. Pokemon Trainer',
    'Okay, here with other in',
    'Oh, God, the unfortunate answer is driving; Pokemon Trainer',
    'Why anyone do anything.',
    'Agent of Cherry Garcia?',
    'Agency Director: What more than eight Jan-Michael Vincent to be joining us?',
    `Naruto, and start shooting at mommy" out of coming for me for, bro. I don'tthink that's`,
    'I mean, that was it?',
    'Dr. Wong picks up with a Dragonball!',
    ",(The Eye-hole Man! I'm a hot dog?",
    "Transition to the heart with black suits with a glass bottle which starts scratching at me a Dragonball, and now they're all right, pokemon card trainer, take IT sometimes!",
    'Got wrapped up to the door to find the agents walk backwards.',
    "We're running late. Where's your family, I'm Stealy. Follow me to do you in",
    "Oh, great. We'll see you just angry at this is using the right."
];

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
	module.exports = GanBotJokes;
}
